pp_app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['domain' => env('DOMAIN'), 'namespace' => 'App\Http\Controllers\MasterWeb'], function () {
    Route::get('/', 'HomeController@index');
});


Route::group(['namespace' => 'App\Http\Controllers\Web'], function () {
    Route::get('/', 'HomeController@index');
});

Route::group(['prefix' => 'pp-admin', 'as' => 'admin.', 'namespace' => 'App\Http\Controllers'], function () {
    Route::group(['middleware' => 'guest:admin'], function () {
        Route::get('/login', 'AuthController@login')->name('login');
        Route::post('/login', 'AuthController@authorise')->name('login.post');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
    });
});

pp_app/app/Models/SiteAdmin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class SiteAdmin extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $hidden = [
        'password'
    ];
}

pp_app/app/Http/Controllers/SiteAdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\SiteAdmin;
use Illuminate\Http\Request;

class SiteAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SiteAdmin  $siteAdmin
     * @return \Illuminate\Http\Response
     */
    public function show(SiteAdmin $siteAdmin)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SiteAdmin  $siteAdmin
     * @return \Illuminate\Http\Response
     */
    public function edit(SiteAdmin $siteAdmin)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\SiteAdmin  $siteAdmin
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SiteAdmin $siteAdmin)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SiteAdmin  $siteAdmin
     * @return \Illuminate\Http\Response
     */
    public function destroy(SiteAdmin $siteAdmin)
    {
        //
    }
}

pp_app/resources/views/siteadmin/layouts/after_login.blade.php
@extends('siteadmin.layouts.app')

@section('body_content')
<div class="dashboard-body">
    <div class="dash-sidebar">
        <div class="sidebar-header">
            <img src="{{ url('handmade/images/logo.png') }}" alt="{{ $site->title }} Logo" title="{{ $site->title }} Logo">
            <span class="toggable">{{ $site->title }}</span>
            <a href="{{ route('admin.dashboard') }}" title="Dashboard"></a>
        </div>
        <ul>
            <li class="current">
                <a href="{{ route('admin.dashboard') }}" title="Dashboard">
                    <i class="icon-dashboard1"></i>
                    <span class="nav-text">Dashboard</span>
                </a>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-images"></i>
                    <span class="nav-text">Sliders</span>
                </a>
                <ul>
                    <li>
                        <a href="">Sliders</a>
                    </li>
                    <li>
                        <a href="">Create New</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-tag"></i> 
                    <span class="nav-text">Posts</span>
                </a>
                <ul>
                    <li>
                        <a href="">Posts</a>
                    </li>
                    <li>
                        <a href="">Create New</a>
                    </li>
                    <li>
                        <a href="">Categories</a>
                    </li>
                    <li>
                        <a href="">Comments</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-file-text2"></i>
                    <span class="nav-text">Pages</span>
                </a>
                <ul>
                    <li>
                        <a href="">Pages</a>
                    </li>
                    <li>
                        <a href="">Create New</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-shopping-bag"></i>
                    <span class="nav-text">Products</span>
                </a>
                <ul>
                    <li>
                        <a href="">Products</a>
                    </li>
                    <li>
                        <a href="">Create New</a>
                    </li>
                    <li>
                        <a href="">Categories</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-cart2"></i>
                    <span class="nav-text">Orders <i class="badge">02</i></span>
                </a>
                <ul>
                    <li>
                        <a href="">Orders</a>
                    </li>
                    <li>
                        <a href="">Create New</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-users"></i>
                    <span class="nav-text">Users</span>
                </a>
                <ul>
                    <li>
                        <a href="">Users</a>
                    </li>
                    <li>
                        <a href="">Create New</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-settings1"></i>
                    <span class="nav-text">Settings</span>
                </a>
                <ul>
                    <li>
                        <a href="">Appearance</a>
                    </li>
                    <li>
                        <a href="">General Settings</a>
                    </li>
                    <li>
                        <a href="">Menu Settings</a>
                    </li>
                    <li>
                        <a href="">Email Settings</a>
                    </li>
                    <li>
                        <a href="">Image Settings</a>
                    </li>
                    <li>
                        <a href="">Form Settings</a>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown">
                <a href="">
                    <i class="icon-user"></i>
                    <span class="nav-text">Profile</span>
                </a>
                <ul>
                    <li>
                        <a href="">Edit Profile</a>
                    </li>
                    <li>
                        <a href="">Change Password</a>
                    </li>
                    <li>
                        <a href="">Logout</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="dash-right">
        <div class="right-header">
            <button type="button" class="nav-bars">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <div>
                <button type="button">
                    <i class="icon-bell"></i>
                </button>
                <button type="button">
                    <i class="icon-user"></i> Hi, {{ auth()->user()->name }}
                </button>
            </div>
        </div>
        @yield('content')
    </div>
</div>
@endsection

pp_app/resources/views/siteadmin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title') | {{ $site->title }}</title>

    <!-- Admin CSS -->
    <link rel="stylesheet" href="{{ url('admin/css/style.css') }}">
    <link rel="stylesheet" href="{{ url('icomoon/style.css') }}">
</head>
<body>
    @yield('body_content')

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" defer></script>
    <script src="{{ url('admin/js/main.js') }}" type="module" defer></script>

    @yield('extra_scripts')
</body>
</html>